---

{{- if .Values.publiccode_validator.ingress.enabled -}}
{{- $fullName := include "publiccode-validator.fullname" . -}}
{{- $servicePort := .Values.publiccode_validator.services.httpPort.port -}}
{{- $ingressPath := .Values.publiccode_validator.ingress.path -}}

apiVersion: extensions/v1beta1

kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ template "publiccode-validator.name" . }}
    chart: {{ template "publiccode-validator.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.publiccode_validator.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.publiccode_validator.ingress.tls }}
  tls:
  {{- range .Values.publiccode_validator.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.publiccode_validator.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: {{ $ingressPath }}
            backend:
              serviceName: {{ $fullName }}-http
              servicePort: {{ $servicePort }}
  {{- end }}
{{- end }}
