---

apiVersion: apps/v1beta2

kind: Deployment
metadata:
  name: {{ template "slackin.fullname" . }}
  labels:
    app: {{ template "slackin.name" . }}
    chart: {{ template "slackin.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.slackin.replicaCount }}
  {{- if .Values.slackin.strategy }}
  {{- with .Values.slackin.strategy }}
  strategy:
    type: {{ toYaml .type }}
    rollingUpdate:
      maxUnavailable: {{ toYaml .rollingUpdate.maxUnavailable }}
      maxSurge: {{ toYaml .rollingUpdate.maxSurge }}
  {{- end }}
  {{- end }}
  revisionHistoryLimit: {{ .Values.slackin.revisionHistoryLimit }}
  selector:
    matchLabels:
      app: {{ template "slackin.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "slackin.name" . }}
        release: {{ .Release.Name }}
      annotations:
        timestamp: "{{ date "20060102150405" .Release.Time }}"
    spec:
      containers:
        - name: slackin
          image: "{{ .Values.global.registry }}{{ .Values.slackin.images.repository }}:{{ tpl .Values.slackin.images.tag . }}"
          imagePullPolicy: {{ .Values.slackin.images.pullPolicy }}

          env:
            - name: SLACK_COC
              value: ""
            - name: SLACK_CHANNELS
              value: ""
            - name: SLACK_SUBDOMAIN
              value: slackin-secrets@azurekeyvault?slack-subdomain
            - name: SLACK_API_TOKEN
              value: slackin-secrets@azurekeyvault?slack-api-token
            - name: GOOGLE_CAPTCHA_SECRET
              value: slackin-secrets@azurekeyvault?google-captcha-secret
            - name: GOOGLE_CAPTCHA_SITEKEY
              value: slackin-secrets@azurekeyvault?google-captcha-sitekey

          ports:
            - name: http
              containerPort: {{ .Values.slackin.services.httpPort.port }}
              protocol: {{ .Values.slackin.services.httpPort.protocol }}

          resources:
{{ toYaml .Values.slackin.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.slackin.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.slackin.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
