---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "slack-registration.fullname" . }}-nginx-configmap
  labels:
    app: {{ template "slack-registration.name" . }}
    chart: {{ template "slack-registration.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  cloud_italia_it.conf: {{ toYaml .Values.slack_registration.nginx_config | indent 4 }}
