---

apiVersion: v1

kind: Service
metadata:
  name: {{ template "slack-registration.fullname" . }}
  labels:
    app: {{ template "slack-registration.name" . }}
    chart: {{ template "slack-registration.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.slack_registration.services.nginx.type }}
  ports:
    - port: {{ .Values.slack_registration.services.nginx.httpPort.servicePort }}
      targetPort: {{ .Values.slack_registration.services.nginx.httpPort.containerPort }}
  selector:
    app: {{ template "slack-registration.name" . }}
    release: {{ .Release.Name }}
