---

global:
  registry: ''

crawler:
  images:
    repository: docker.io/italia/developers-italia-backend
    tag: latest
    pullPolicy: Always

  env:
    elastic_url: "http://developersitalia-master:9200"
    elastic_user: "elastic"

  cronjob_schedule: "0 0 * * *"

  resources:
    # For each of the following objects, set limits
    # removing the curly brackets after resources and
    # uncommenting the lines below.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  nodeSelector: {}

  tolerations: {}

  affinity: {}
