---

apiVersion: v1

kind: Service
metadata:
  name: {{ template "crawler.fullname" . }}
  labels:
    app: {{ template "crawler.name" . }}
    chart: {{ template "crawler.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.crawler.services.nginx.type }}
  ports:
    - port: {{ .Values.crawler.services.nginx.httpPort.servicePort }}
      targetPort: {{ .Values.crawler.services.nginx.httpPort.containerPort }}
  selector:
    app: {{ template "crawler.name" . }}
    release: {{ .Release.Name }}
