---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "crawler.fullname" . }}-nginx-configmap
  labels:
    app: {{ template "crawler.name" . }}
    chart: {{ template "crawler.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  crawler.conf: {{ toYaml .Values.crawler.nginx_config | indent 4 }}
