---

apiVersion: v1

kind: PersistentVolumeClaim
metadata:
  name: crawler
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: azurefile-premium
  resources:
    requests:
      storage: 100Gi
