---

apiVersion: v1

kind: PersistentVolumeClaim
metadata:
  name: onboarding
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-premium-custom
  resources:
    requests:
      storage: 1Gi
