---

apiVersion: v1

kind: PersistentVolumeClaim
metadata:
  name: crawler-data
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-premium-custom
  resources:
    requests:
      storage: 50Gi

---

apiVersion: v1

kind: PersistentVolumeClaim
metadata:
  name: crawler-output
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: azurefile-standard
  resources:
    requests:
      storage: 1Gi
