---

apiVersion: v1

kind: Service
metadata:
  name: {{ template "slackin.fullname" . }}-http
  labels:
    app: {{ template "slackin.name" . }}
    chart: {{ template "slackin.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.slackin.services.httpPort.type }}
  ports:
    - name: http
{{ toYaml .Values.slackin.services.httpPort | indent 6 }}
  selector:
    app: {{ template "slackin.name" . }}
    release: {{ .Release.Name }}
